/* #include_block */
#include "meielement.h"
#include "meidocument.h"
/* #include_block */

/* <note> */
        std::string getLayerIdent();
        MeiElement* getLayer();

        std::string getStaffIdent();
        MeiElement* getStaff();

        MeiElement* getSystem();

/* </note> */

/* <rest> */
        std::string getLayerIdent();
        MeiElement* getLayer();

        std::string getStaffIdent();
        MeiElement* getStaff();

        MeiElement* getSystem();

/* </rest> */

/* <chord> */
        std::string getLayerIdent();
        MeiElement* getLayer();

        std::string getStaffIdent();
        MeiElement* getStaff();

        MeiElement* getSystem();

/* </chord> */

/* <barLine> */
        std::string getLayerIdent();
        MeiElement* getLayer();

        std::string getStaffIdent();
        MeiElement* getStaff();

        MeiElement* getSystem();

/* </barLine> */

/* <clef> */
        std::string getLayerIdent();
        MeiElement* getLayer();

        std::string getStaffIdent();
        MeiElement* getStaff();

        MeiElement* getSystem();

/* </clef> */

/* <custos> */
        std::string getLayerIdent();
        MeiElement* getLayer();

        std::string getStaffIdent();
        MeiElement* getStaff();

        MeiElement* getSystem();

/* </custos> */

/* <pad> */
        std::string getLayerIdent();
        MeiElement* getLayer();

        std::string getStaffIdent();
        MeiElement* getStaff();

        MeiElement* getSystem();

/* </pad> */

/* <space> */
        std::string getLayerIdent();
        MeiElement* getLayer();

        std::string getStaffIdent();
        MeiElement* getStaff();

        MeiElement* getSystem();

/* </space> */