language: cpp
if: (branch = master AND type IN (pull_request, cron)) OR (branch = develop)
# Add more platforms here as they become needed.
matrix:
  include:
    # Linux Installation.
    - os: linux
      env:
        - MATRIX_EVAL="sudo apt-get install build-essential software-properties-common git unzip wget apt-utils uuid-dev -y"
        - LIBMEI_EVAL="cmake -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_LIBRARY_PATH=gtest-$GTEST_VERSION -DCMAKE_INCLUDE_PATH=gtest-$GTEST_VERSION/include . && make"
    # Mac Installation.
    - os: osx
      env:
        # Stop Homebrew from auto-updating when installating an app.
        - HOMEBREW_NO_AUTO_UPDATE="1"
        - MATRIX_EVAL="brew install ossp-uuid"
        - LIBMEI_EVAL="cmake -DCMAKE_FIND_FRAMEWORK=LAST && make"
before_install:
    # Install OS dependencies.
    - eval "${MATRIX_EVAL}"
    # Edit the GTEST version here, to update the unittest framework.
    - export GTEST_VERSION=1.8.0
install:
  # Install GTEST.
  - wget https://github.com/google/googletest/archive/release-${GTEST_VERSION}.zip
  - unzip -q ./release-${GTEST_VERSION}.zip
  - cd googletest-release-${GTEST_VERSION}
  - cmake .
  - make
  # Install LibMEI.
  - cd ..
  - eval "${LIBMEI_EVAL}"
script:
  # Run Unittests.
  - make test
notifications:
  email: false
  slack:
    secure: uc59AHlohSmJvpAPcLLiNJS0W83iZ2vPxTPrkzUANdSL77UGpDiM1KbrbHhPFp0FBWPCQ9uhGURIAdEV0oSE6iFaeu95xgGloX3k5ozsw6eD1qXXunSYX5fztPdcB5zuDiU6haLUU/Pu6/Yen8n9GaDxMjmGsUGt3zj87l4xJDs=
