/* #include_block */
#include "meielement.h"
#include "meidocument.h"
/* #include_block */

/* <note> */
        std::string getLayerIdent();
        MeiElement* getLayer();

        std::string getStaffIdent();
        MeiElement* getStaff();

        MeiElement* getSystem();

/* </note> */

/* <rest> */
        std::string getLayerIdent();
        MeiElement* getLayer();

        std::string getStaffIdent();
        MeiElement* getStaff();

        MeiElement* getSystem();

/* </rest> */